### PR TITLE
Fix dropdown with nothing selected throwing on pre-selecting afterwards

### LINKED ISSUE #3498: InvalidOperationException when pressing a key in a dropdown menu when settings SearchTextBox isn't empty
**Describe the bug:**
- Open the settings panel
- Search for an option with a dropdown using the `SearchTextBox`
- Open the dropdown
- Press any key, the game will throw an `InvalidOperationException`

**Screenshots or videos showing encountered issue:** [Video](https://drive.google.com/file/d/1cNvBwZNV-J8KYeGqjC8jmm2SpsHp7Gkq/view?usp=sharing)

**Logs:** [runtime.log](https://github.com/ppy/osu/files/4558015/runtime.log)

### PR DESCRIPTION
**Pull request by iiSaLMaN**
Technically closes #3498, but will be more corrected with ppy/osu#8912 being fixed.

There may normally be dropdowns with no items selected inside them, this is aiming to fix the exception thrown when pre-selecting by pressing on the keyboard there.

### CODE REVIEW

File: osu.Framework/Graphics/UserInterface/Dropdown.cs [hunk 1]
```diff
@@ -525,9 +530,8 @@ protected override bool OnKeyDown(KeyDownEvent e)
                 if (!drawableMenuItemsList.Any())
                     return base.OnKeyDown(e);
 
-                var currentPreselected = drawableMenuItemsList.FirstOrDefault(i => i.IsPreSelected) ?? drawableMenuItemsList.First(i => i.IsSelected);
-
-                var targetPreselectionIndex = drawableMenuItemsList.IndexOf(currentPreselected);
+                var currentPreselected = PreselectedItem;
+                var targetPreselectionIndex = currentPreselected == null ? NULL_ITEM_INDEX : drawableMenuItemsList.IndexOf(currentPreselected);
```
Comment (smoogipoo) [inline osu.Framework/Graphics/UserInterface/Dropdown.cs:534]: `IndexOf()` already returns -1 when the item isn't found, so it's probably ok to remove the null check
