### PR TITLE
Make Textbox's background colours settable

### LINKED ISSUE #2114: TextBox's BackgroundUnfocused / BackgroundFocused should be settable
Currently they are get only and also fail to set the initial colour if only available after async load.

### PR DESCRIPTION
**Pull request by HoutarouOreki**
Resolves #2114.

### CODE REVIEW

File: osu.Framework/Graphics/UserInterface/TextBox.cs [hunk 1]
```diff
@@ -64,9 +64,32 @@ public class TextBox : TabbableContainer, IHasCurrentValue<string>
...
+        protected Color4 BackgroundCommit { get; set; } = new Color4(249, 90, 255, 200);
+
+        protected Color4 BackgroundFocused
+        {
+            get => backgroundFocused;
+            set
+            {
+                backgroundFocused = value;
+                if (HasFocus)
+                    Background.FadeColour(value, Background.IsLoaded ? 200 : 0);
```
Comment (peppy) [inline osu.Framework/Graphics/UserInterface/TextBox.cs]: this code should not exist in two places. make an `updateFocus()` method and call from everywhere.

File: osu.Framework/Graphics/UserInterface/TextBox.cs [hunk 2]
```diff
@@ -64,9 +64,32 @@ public class TextBox : TabbableContainer, IHasCurrentValue<string>
...
+        }
+
+        protected Color4 BackgroundUnfocused
+        {
+            get => backgroundUnfocused;
+            set
+            {
+                backgroundUnfocused = value;
+                if (!HasFocus)
+                    Background.FadeColour(value, Background.IsLoaded ? 200 : 0);
```
Comment (peppy) [inline osu.Framework/Graphics/UserInterface/TextBox.cs]: same goes for this.
