### PR TITLE
Reintroduce & fix gamewindow refactor

### LINKED ISSUE #1102: Refactor GameWindow to not extend OpenTK.GameWindow
As part of the upcoming iOS/Android builds, we will need to look at refactoring our `GameWindow` class.  It currently extends `OpenTK.GameWindow`, which is primarily for desktop platforms.  Attempting to use it on iOS or Android throws a `NotImplementedException`.

Proposal is to decouple our `GameWindow` class from `OpenTK.GameWindow` and instead use an `OpenTK.IGameWindow` property that's assigned the correct implementation for the platform.  OpenTK will assist us with most of this on the desktop side, but iOS/Android will need to manually instantiate and assign the window (not a big deal).

### PR DESCRIPTION
**Pull request by FreezyLemon**
Reintroduces the changes and fixes the windows bug from #1420 .
This should probably still be tested on all other platforms.

Edit: Closes #1102 (again).

### CODE REVIEW

File: osu.Framework/Platform/DesktopGameWindow.cs [hunk 1]
```diff
@@ -26,11 +27,19 @@ public class DesktopGameWindow : GameWindow
...
+
         public readonly BindableBool MapAbsoluteInputToWindow = new BindableBool();
 
         public DesktopGameWindow()
             : base(default_width, default_height)
         {
+            Resize += OnResize;
+            Move += OnMove;
+
+            Context.MakeCurrent(null);
```
Comment (smoogipoo) [inline osu.Framework/Platform/DesktopGameWindow.cs]: Let's move this to the base `GameWindow`, since we have an abstract `Context` now.

**Comment by smoogipoo** [comment]
Tested on macOS and Windows, looks ok to me. 👍
