### PR TITLE
Fix macOS cursor reappearing on focus lost

### LINKED ISSUE #1703: Mac native cursor reappears on OS notification display
We likely need to continuously poll to hide the cursor to avoid it getting in a weird state.

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/60738653-mac-native-cursor-reappears-on-os-notification-display?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by swoolcock**
Fixes an issue where the macOS cursor would reappear on focus switch.

Delay is required to ensure the cursor rects are invalidated while the window has the focus, otherwise the cursor will not disappear until the user moves the mouse.

Resolves #1703

### CODE REVIEW

**Comment by peppy** [comment]
Is there any documentation/stackoverflow you referenced when fixing this? Would be good to have a reference in the code to point to where the solution came from, if it's a known/accepted issue.

**Comment by swoolcock** [comment]
`invalidateCursorRectsForView:` gets called by OpenTK when you change the cursor mode, so I was pretty sure that's all that needed to happen.  Rather than trying to get hold of the content view and send the message directly I figured it was easier to just reflect the OpenTK function that does it.

File: osu.Framework/Platform/MacOS/MacOSGameWindow.cs [hunk 1]
```diff
@@ -21,14 +22,18 @@ internal class MacOSGameWindow : DesktopGameWindow
...
 
         private object nativeWindow;
 
         public MacOSGameWindow()
         {
             Load += OnLoad;
+            FocusedChanged += focusedChanged;
         }
 
+        private void focusedChanged(object sender, EventArgs e) => Task.Delay(300).ContinueWith(arg => methodInvalidateCursorRects.Invoke(nativeWindow, new object[0]));
```
Comment (peppy) [inline osu.Framework/Platform/MacOS/MacOSGameWindow.cs]: if `arg` isn't used make it `_` instead.

also i really think you should have an inline comment on the line above this explaining what it's doing. so people don't have to find the PR or commit to know why this exists.
