### PR TITLE
Fix Uniform.Value's setter not setting HasChanged to true

### LINKED ISSUE #2750: Setting Uniform.Value does not work as expected
It is publicly settable however it does not set `HasChanged = true`, making the setter not work at all.

### PR DESCRIPTION
**Pull request by KoziLord**
Closes #2750.

### CODE REVIEW

File: osu.Framework/Graphics/Shaders/Uniform.cs [hunk 1]
```diff
@@ -14,7 +14,17 @@ public class Uniform<T> : IUniformWithValue<T>
 
         public bool HasChanged { get; private set; } = true;
 
-        public T Value;
+        private T _value;
```
Comment (smoogipoo) [inline osu.Framework/Graphics/Shaders/Uniform.cs]: Should be `value`, by convention with the rest of the framework.

File: osu.Framework/Graphics/Shaders/Uniform.cs [hunk 2]
```diff
@@ -14,7 +14,17 @@ public class Uniform<T> : IUniformWithValue<T>
...
+
+        public T Value
+        {
+            get => _value;
+            set
+            {
+                _value = value;
```
Comment (smoogipoo) [inline osu.Framework/Graphics/Shaders/Uniform.cs]: Should probably have an equality check as in `UpdateValue()`. `UpdateValue()` should itself update the private member to avoid a redundant equality comparison imo.

File: osu.Framework/Graphics/Shaders/Uniform.cs [hunk 3]
```diff
@@ -43,7 +53,7 @@ public void Update()
             HasChanged = false;
         }
 
-        ref T IUniformWithValue<T>.GetValueByRef() => ref Value;
+        ref T IUniformWithValue<T>.GetValueByRef() => ref _value;
         T IUniformWithValue<T>.GetValue() => Value;
```
Comment (smoogipoo) [inline osu.Framework/Graphics/Shaders/Uniform.cs]: Nitpick: would prefer this was updated to reference `value` (also the equality check in `UpdateValue()`).

**Comment by KoziLord** [comment]
As mentioned on Discord; Currently doing comparison on `T` results in a boxing call to `ValueType.Equals(object? obj)`, I propose adding the `IEquatable<T>` constraint to `IUniformWithValue<T>` and everything that implements it to avoid it.

**Comment by smoogipoo** [comment]
Yeah, add the constraint.

**Comment by smoogipoo** [comment]
What's the difference in performance by `.Value` calling `UpdateValue(ref value)` or vice-versa? If there's not much, it would eliminate the code dupe.

**Comment by KoziLord** [comment]
The difference in performance will depend on the size of the T struct I'd imagine.
The general tip is to only pass by reference if `T` is bigger than `sizeof(IntPtr) * 2` (8 bytes on x86, 16 bytes on x64).

Potentially the equality check would also be an issue (unless it gets inlined) since it could cause an unnecessary copy of a big struct.
If `IEquatable<T>` exposed something like `T.EqualsByRef(ref T)` the generic method could be rewritten to use either `Equals()` or `EqualsByRef()` depending on the `sizeof(T)`, this coupled with the fact that `if (sizeof(T) > 16)` is checked during JIT compilation would allow for this check to be free as the JIT will elide the invalid branch.

However I don't think that anything bigger than a Matrix4x4 is used with Uniforms so I think only passing by value is fine and I agree to removing `UpdateValue(ref value)`.
