### PR TITLE
Catch exceptions thrown during dynamic compilation runtime

### LINKED ISSUE #1284: TestBrowser should not crash when in interactive mode
Our dynamic compilation workflow is pretty good, until you make a mistake and cause the game to hard-crash.

TestBrowser should gracefully catch exceptions so it itself does not crash when a coding error is made.

### PR DESCRIPTION
**Pull request by peppy**
Handles any exceptions thrown in the loaded TestCase's Update or UpdateSubTree.

Closes #1284.

### CODE REVIEW

File: osu.Framework/Testing/DynamicClassCompiler.cs [hunk 1]
```diff
@@ -130,34 +132,29 @@ private void recompile()
...
                         if (diagnostic.Severity < DiagnosticSeverity.Error)
                             continue;
-                        Logger.Log(diagnostic.ToString(), LoggingTarget.Runtime, LogLevel.Error);
+
+                        CompilationFailed?.Invoke(new Exception(diagnostic.ToString()));
                     }
                 }
             }
 
-            CompilationFinished?.Invoke(compiledType);
```
Comment (smoogipoo) [inline osu.Framework/Testing/DynamicClassCompiler.cs]: Do finishing compilations do anything now?

Comment (smoogipoo) [reply osu.Framework/Testing/DynamicClassCompiler.cs]: my bad it was moved above...
