### PR TITLE
Synchronously exit `ThreadRunner` threads

### LINKED ISSUE #5216: `ThreadRunner.Stop()` is not safe in multithreaded mode
Alternate title: Audio thread can exit while update thread accesses its resources, causing an `ObjectDisposedException`
Sentry Issue: [OSU-G6](https://sentry.ppy.sh/organizations/ppy/issues/547/?referrer=github_integration)
Originally discovered in https://github.com/ppy/osu-framework/pull/5211#issuecomment-1141045506.

[`ThreadRunner.Stop()`](https://github.com/ppy/osu-framework/blob/f51ace62599d9e4c74bbfae9e9a8868d3609a3d0/osu.Framework/Platform/ThreadRunner.cs#L138-L161) will exit the threads "asynchronously", requesting each thread to exit, and will then block until all threads exit. This is a problem as `UpdateThread` is dependant on `AudioThread` (other combinations don't seem to throw, tested by manually exiting threads while the game is running). If `AudioThread` exits before `UpdateThread`, and a drawable requests a resource (in this case, `SampleStore.Get` in BDL) it'll fail with an `ObjectDisposedException`.

Interestingly, pausing threads is done [synchronously](https://github.com/ppy/osu-framework/blob/da15cdeef0f37685d4130e603c45c60fc96277a7/osu.Framework/Threading/GameThread.cs#L300-L318), in reverse order: `Draw`, `Update`, `Audio`, `Input`

https://github.com/ppy/osu-framework/blob/f51ace62599d9e4c74bbfae9e9a8868d3609a3d0/osu.Framework/Platform/ThreadRunner.cs#L210-L215

Changing `ThreadRunner.Stop()` / `GameThread.Exit()` to exit synchronously and in reverse order fixes the issue.

To repro:
- checkout #5211 (without it, the exit is scheduled, and the race condition is less likely to occur)
- apply this diff:
```diff
diff --git a/osu.Framework.Tests/Program.cs b/osu.Framework.Tests/Program.cs
index 8fb25e4db..5eddd0a62 100644
--- a/osu.Framework.Tests/Program.cs
+++ b/osu.Framework.Tests/Program.cs
@@ -3,6 +3,7 @@

 using System;
 using System.Linq;
+using System.Threading;
 using osu.Framework.Platform;

 namespace osu.Framework.Tests
@@ -20,7 +21,23 @@ public static void Main(string[] args)
                 if (benchmark)
                     host.Run(new AutomatedVisualTestGame());
                 else
-                    host.Run(new VisualTestGame());
+                    host.Run(new BuggyGame());
+            }
+        }
+
+        private class BuggyGame : TestGame
+        {
+            protected override bool OnExiting()
+            {
+                Scheduler.Add(() =>
+                {
+                    // pretend that a lot of work is done here, eg. adding and loading new drawables...
+                    // a.k.a. allow the audio thread to exit.
+                    Thread.Sleep(10);
+                    Audio.Samples.Get("long.mp3");
+                });
+
+                return false;
             }
         }
     }
```

### PR DESCRIPTION
**Pull request by Susko3**
- Closes #5216
- Fixes [OSU-G6](https://sentry.ppy.sh/organizations/ppy/issues/547/?referrer=github_integration)

I've omitted the timeout as it will break the synchronicity of the exiting process. If the timeout is something that is wanted, it can be added back, but `throw`ing instead of just logging (and should probably apply to the `while` loops as well).

### CODE REVIEW

File: osu.Framework/Threading/GameThread.cs [hunk 1]
```diff
@@ -341,9 +341,22 @@ internal void WaitForState(GameThreadState targetState)
             }
             else
             {
-                while (state.Value != targetState)
-                    Thread.Sleep(1);
+                switch (targetState)
+                {
+                    case GameThreadState.Exited:
+                    case GameThreadState.Paused:
+                        Thread.Join();
```
Comment (bdach) [inline osu.Framework/Threading/GameThread.cs:348]: I kind of don't like that `Join()` is placed here... would prefer it to be back in `ThreadRunner` if feasible, for two reasons:

* `WaitForState()` doing anything else than waiting for a thread's state to change to the desired one seems wrong/weird
* `GameThread` joining... itself? is also reading really weird to me.

Comment (Susko3) [reply osu.Framework/Threading/GameThread.cs:348]: > `WaitForState()` doing anything else than waiting for a thread's state to change to the desired one seems wrong/weird

It's just an optimization, taking advantage of the native thread [immediately exiting](https://github.com/ppy/osu-framework/blob/4b8f595630dd7281472a07619e0066bd1beeeceb/osu.Framework/Threading/GameThread.cs#L419-L425) once it reaches those states.

> `GameThread` joining... itself? is also reading really weird to me.

That's not really fair to say, as `WaitForState()` is never called from within a native thread.

Comment (peppy) [reply osu.Framework/Threading/GameThread.cs:348]: I'm okay with the change in structure personally, but I'm not sure about dropping the timeout parameter. Was there a reason this couldn't remain as a safety measure? It was intended to avoid the game potentially getting in a state where the process is stuck and a user needs to forcefully quit from task manager.

Comment (peppy) [reply osu.Framework/Threading/GameThread.cs:348]: I just saw your reasoning for doing so.

I'd much rather it returns as a `throw` if that's what is required.

**Comment by Susko3** [comment]
Discovered a potential race condition in the current code, will push a fix.
Happens due to `Thread = null` and setting exit state being [far apart](https://github.com/ppy/osu-framework/blob/4b8f595630dd7281472a07619e0066bd1beeeceb/osu.Framework/Threading/GameThread.cs#L499-L512).

Not sure why `Thread = null` is set this early, I'd expect it to be done as a cleanup step when the native thread exits (eg. [here](https://github.com/ppy/osu-framework/blob/4b8f595630dd7281472a07619e0066bd1beeeceb/osu.Framework/Threading/GameThread.cs#L425)). Out of scope, I don't want to accidentally break anything.

**Comment by peppy** [comment]
Looks correct now, but will wait for a second opinion.

**Review by bdach — APPROVED** [review]
makes sense to me

**Review by peppy — APPROVED** [review]
