### PR TITLE
Adjust GetBackwardWordAmount and GetForwardWordAmount to take symbols into account

### LINKED ISSUE #6483: Make Ctrl+Backspace break on symbols
### Type

Game behaviour

### Bug description

Ctrl + Backspace is a shortcut frequently used to quickly delete a word, implemented across many different text editors.

Right now, it seems to delete everything to the left of the cursor until it encounters a space. This is inconsistent with most implementations, which also breaks when a symbol is encountered. In beatmap searching, for example, `author=kongehund` should break on `=`, such that the resulting text is `author=`.

### Screenshots or videos

_No response_

### Version

2024.1224.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18290346/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by AleXu224**
Fixes #6483 

https://github.com/user-attachments/assets/53665dce-9788-4f94-9dd0-e3a4dc8ecb35

### CODE REVIEW

**Comment by peppy** [comment]
Seems logical.

**Comment by smoogipoo** [comment]
When selecting forward words, it should also select the symbol (using macOS as example here, don't have Windows to test with atm):

https://github.com/user-attachments/assets/74af78f4-c41b-47d3-9ffe-37ff95d71ee3

https://github.com/user-attachments/assets/6ccfe5de-4b6a-476b-9370-2cae1ee2bf0a

File: osu.Framework/Graphics/UserInterface/TextBox.cs [hunk 1]
```diff
@@ -436,11 +447,23 @@ protected int GetBackwardWordAmount()
...
+
+            // Skip one character if it is a symbol to avoid cases like "author=<cursor>" requiring two taps
+            if (isCharacterSymbol(text[searchPrev]))
+                searchPrev--;
+
+            if (searchPrev <= 0) return -selectionEnd;
+
+            Func<char, bool> searchFunc = isCharacterSymbol(text[searchPrev]) ? isCharacterSymbol : isCharacterAlphanumeric;
+            while (searchPrev > 0 && searchFunc(text[searchPrev]))
+                searchPrev--;
```
Comment (smoogipoo) [inline osu.Framework/Graphics/UserInterface/TextBox.cs:464]: This function in general is quite hard to understand and prove for correctness, imo. I wonder if all of these can be combined into the one while loop? Maybe including the whitespace case from above?

Here's another weird case (multiple symbols before alphanumeric):

https://github.com/user-attachments/assets/056b69b7-94df-479c-b558-c2992a7e8e41

https://github.com/user-attachments/assets/3461e0e0-8ff5-482e-9d3b-d07b62456cad

File: osu.Framework/Graphics/UserInterface/TextBox.cs [hunk 2]
```diff
@@ -428,6 +429,16 @@ public bool SelectAll()
...
 
+        private bool isCharacterSymbol(char character)
+        {
+            return !character.IsAlphaNumeric() && !character.IsWhitespace();
+        }
+
+        private bool isCharacterAlphanumeric(char character)
+        {
+            return character.IsAlphaNumeric();
+        }
```
Comment (smoogipoo) [inline osu.Framework/Graphics/UserInterface/TextBox.cs:440]: Should make these `static`.

**Review by smoogipoo — CHANGES_REQUESTED** [review]

**Comment by AleXu224** [comment]
> When selecting forward words, it should also select the symbol (using macOS as example here, don't have Windows to test with atm):
> Screen.Recording.2025-01-21.at.14.04.09.mov
> Screen.Recording.2025-01-21.at.14.04.31.mov

When making this PR I used Visual Studio Code as a reference, sadly it looks like the way this is implemented in apps is inconsistent.
I just tested it in firefox, notepad++, discord and vscode and they all had different behavior.
It looks like you are using a browser search bar to test it, should I copy the way that does it or stick with the current implementation ?

**Comment by peppy** [comment]
> It looks like you are using a browser search bar to test it, should I copy the way that does it or stick with the current implementation ?

I'd just choose one and go with it. Probably matching smoogi's proposal is fine until someone has a problem with it. It's not important in the scheme of things.

**Comment by AleXu224** [comment]
@smoogipoo Sorry for the ping. Any updates on this ? I wasn't quite sure if I needed to re-request a review and just waited for a while.

**Comment by smoogipoo** [comment]
I've been looking into documenting the behaviour, and from a purely explanatory point of view, I believe something like the following makes sense:

```diff
diff --git a/osu.Framework/Graphics/UserInterface/TextBox.cs b/osu.Framework/Graphics/UserInterface/TextBox.cs
index e689ff8059..348226332d 100644
--- a/osu.Framework/Graphics/UserInterface/TextBox.cs
+++ b/osu.Framework/Graphics/UserInterface/TextBox.cs
@@ -473,23 +473,37 @@ protected int GetBackwardWordAmount()
 
             WordTraversalStep currentStep = WordTraversalStep.InitialWhitespace;
             bool finished = false;
+
             while (!finished && searchPrev >= 0)
             {
                 char character = text[searchPrev];
+
                 switch (currentStep)
                 {
                     case WordTraversalStep.InitialWhitespace:
                         if (character == ' ')
                             searchPrev--;
                         else
+                            currentStep = WordTraversalStep.SymbolOrAlphanumerical;
+                        break;
+
+                    case WordTraversalStep.SymbolOrAlphanumerical:
+                        searchPrev--;
+
+                        if (isCharacterAlphanumeric(character))
+                            currentStep = WordTraversalStep.Alphanumerical;
+                        else if (isCharacterSymbol(character))
                             currentStep = WordTraversalStep.Symbol;
+
                         break;
+
                     case WordTraversalStep.Symbol:
                         if (isCharacterSymbol(character))
                             searchPrev--;
                         else
-                            currentStep = WordTraversalStep.Alphanumerical;
+                            finished = true;
                         break;
+
                     case WordTraversalStep.Alphanumerical:
                         if (isCharacterAlphanumeric(character))
                             searchPrev--;
@@ -516,23 +530,37 @@ protected int GetForwardWordAmount()
 
             WordTraversalStep currentStep = WordTraversalStep.InitialWhitespace;
             bool finished = false;
+
             while (!finished && searchNext < text.Length)
             {
                 char character = text[searchNext];
+
                 switch (currentStep)
                 {
                     case WordTraversalStep.InitialWhitespace:
                         if (character == ' ')
                             searchNext++;
                         else
+                            currentStep = WordTraversalStep.SymbolOrAlphanumerical;
+                        break;
+
+                    case WordTraversalStep.SymbolOrAlphanumerical:
+                        searchNext++;
+
+                        if (isCharacterAlphanumeric(character))
                             currentStep = WordTraversalStep.Alphanumerical;
+                        else if (isCharacterSymbol(character))
+                            currentStep = WordTraversalStep.Symbol;
+
                         break;
+
                     case WordTraversalStep.Alphanumerical:
                         if (isCharacterAlphanumeric(character))
                             searchNext++;
                         else
-                            currentStep = WordTraversalStep.Symbol;
+                            finished = true;
                         break;
+
                     case WordTraversalStep.Symbol:
                         if (isCharacterSymbol(character))
                             searchNext++;
@@ -1862,6 +1890,7 @@ public enum TextSelectionType
         private enum WordTraversalStep
         {
             InitialWhitespace,
+            SymbolOrAlphanumerical,
             Symbol,
             Alphanumerical,
         }

```

Where the explanation that we take all whitespace characters until a symbol or a/n is found, and then continue taking all of that type of character. I apologise if this is going in circles and is what the original implementation did here. Here's some comparisons:

| Platform | Tool | Video |
| --- | --- | --- |
| Windows | Explorer | <video src="https://github.com/user-attachments/assets/2d07a938-c6b3-4a49-8984-ba9242ad6611"> |
| Windows | Visual Studio 2022 | <video src="https://github.com/user-attachments/assets/e81d30c2-f239-4fb0-a372-2b57f7847bb0"> |
| Windows | Notepad | <video src="https://github.com/user-attachments/assets/988a673e-8382-4d32-b816-e6ba8ad45bea"> |
| Windows | Winforms | <video src="https://github.com/user-attachments/assets/f9b0b0dd-3189-4052-a449-598196086e41"> |
| macOS | TextEdit | <video src="https://github.com/user-attachments/assets/057ee2ff-683d-4fc0-8c0c-1a02de4e0aef"> |
| macOS | Xcode 16 Beta | <video src="https://github.com/user-attachments/assets/25157ec1-9375-469a-90f7-a250f9fb63fd"> |
| Linux | VSCode | <video src="https://github.com/user-attachments/assets/96af1874-7ec0-4beb-9609-757d6c30a749"> |
| Any | Firefox | <video src="https://github.com/user-attachments/assets/963d6ae7-77ae-4234-a35f-1f978fc9453e"> |
| Any | Discord | <video src="https://github.com/user-attachments/assets/113999eb-25c8-4026-9340-3eca2858a290"> |
| Any | Rider | <video src="https://github.com/user-attachments/assets/abc88603-d868-45c3-a106-95f4924077e0"> |

| osu-framework version | Video |
| --- | --- |
| master | <video src="https://github.com/user-attachments/assets/35ee82fb-3aa9-4823-aaa7-113ea100423d"> |
| this PR | <video src="https://github.com/user-attachments/assets/7c757db9-1b90-4765-abb1-26eca7dbde91"> |
| suggested | <video src="https://github.com/user-attachments/assets/80b04dd8-0675-464c-a410-31ccc2df18f7"> |

My suggestion matches Rider and is close to how Windows behaves, _but_ given that every single UI system implements this in its own way, I'm primarily looking for ease of explanation in isolation.

Curious on @peppy 's thoughts too

**Comment by peppy** [comment]
I'm fine with whatever you decide on 👍 . It's not really something 99% of users will hit.

**Comment by smoogipoo** [comment]
Sorry for the force push. I originally started out trying to make it more Windows-like - in particular I felt like selecting the trailing whitespace is important to preserve invertibility when you go forward and back. [Here are those changes](https://gist.github.com/smoogipoo/4843dc4fe4de84a392edde6c955854b9) that can be applied onto https://github.com/ppy/osu-framework/pull/6496/commits/ac28c147032ea5acbbd9eaa68021830a57dbfc6d .

I don't feel strongly in that as I originally thought, so I think this is fine as it is with my suggestion from above applied. I've made some additional refactoring to centralise the algorithm, and swapped to using `char.IsLetterOrDigit()` instead of the markdig helpers (hate using external library helpers for stuff like this).

I believe this is good to go from me. @peppy review's all yours.

**Review by peppy — APPROVED** [review]

**Comment by AleXu224** [comment]
I probably don't have much say in this but I feel like the current approach is somewhat flawed:
| issue | demo |
| ----- | -------|
| ``Let's`` and ``Don't`` take 3 taps to remove | <video src="https://github.com/user-attachments/assets/0fef2811-a98e-44c2-b6c2-cbcd35cbd130"> |
| Going through all of this in one swoop doesn't feel right to me | <video src="https://github.com/user-attachments/assets/f9e1b11a-8c46-4580-9808-679dcf2129c2"> |
| I feel like these two examples should behave the same | <video src="https://github.com/user-attachments/assets/f83e586b-4aed-4075-9dfe-9e538ed690d0"> |

I would love if we could at least have it done the following way since it feels (at least to me) like the better option in the context of osu:
```diff
diff --git a/osu.Framework/Graphics/UserInterface/TextBox.cs b/osu.Framework/Graphics/UserInterface/TextBox.cs
index 71b2a5f51..2548d671d 100644
--- a/osu.Framework/Graphics/UserInterface/TextBox.cs
+++ b/osu.Framework/Graphics/UserInterface/TextBox.cs
@@ -490,6 +490,15 @@ private static int findNextWord(string text, int position, int direction)
 
                         continue;
 
+                    case WordTraversalStep.Symbol:
+                        if (char.IsLetterOrDigit(character))
+                            currentStep = WordTraversalStep.LetterOrDigit;
+                        else if (char.IsWhiteSpace(character))
+                            break;
+
+                        position += direction;
+                        continue;
+
                     case WordTraversalStep.LetterOrDigit:
                         if (char.IsLetterOrDigit(character))
                         {
@@ -498,13 +507,6 @@ private static int findNextWord(string text, int position, int direction)
                         }
 
                         break;
-
-                    case WordTraversalStep.Symbol:
-                        if (char.IsLetter(character) || char.IsWhiteSpace(character))
-                            break;
-
-                        position += direction;
-                        continue;
                 }
 
                 break;
```
With the proposed changes those 3 examples would look like this:
| example |
| --- |
| <video src="https://github.com/user-attachments/assets/80f1ddc9-f54f-4c5c-bcd5-f9230d18880e"> |
| <video src="https://github.com/user-attachments/assets/7c6e6694-bdbf-4fc3-8b1d-5d07c979cc32"> |
| <video src="https://github.com/user-attachments/assets/35046477-a72f-40b1-8b04-e7cf692baa3f"> |

And your example:

https://github.com/user-attachments/assets/84d29a6a-fc9b-4dcd-9017-21abaeaac64a

I am so sorry for making such a comment when it is so close to completion but ending it the way that is it right now would leave a sour taste in my mouth.

<details>
<summary>Here's the changes and the tests fixed since our schedules don't quite align</summary>

```diff
diff --git a/osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs b/osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
index d5f90fdf3..fb8cd3331 100644
--- a/osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
+++ b/osu.Framework.Tests/Visual/UserInterface/TestSceneTextBox.cs
@@ -392,12 +392,8 @@ public void TestPreviousWordDeletionWithSymbols()
 
             AddStep("insert text", () => textBox.InsertString("author=test123 $$$aaa 5.5..."));
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
-            AddAssert("some text remains", () => textBox.Text == "author=test123 $$$aaa 5.5");
-            AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("some text remains", () => textBox.Text == "author=test123 $$$aaa 5.");
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
-            AddAssert("some text remains", () => textBox.Text == "author=test123 $$$aaa 5");
-            AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("some text remains", () => textBox.Text == "author=test123 $$$aaa ");
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("some text remains", () => textBox.Text == "author=test123 $$$");
@@ -406,8 +402,6 @@ public void TestPreviousWordDeletionWithSymbols()
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("some text remains", () => textBox.Text == "author=");
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
-            AddAssert("some text remains", () => textBox.Text == "author");
-            AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("text is empty", () => textBox.Text.Length == 0);
             AddStep("delete last word", () => InputManager.Keys(PlatformAction.DeleteBackwardWord));
             AddAssert("text is empty", () => textBox.Text.Length == 0);
@@ -499,18 +493,12 @@ public void TestNextWordDeletionWithSymbols()
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("some text remains", () => textBox.Text == "=test123 $$$aaa 5.5...");
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
-            AddAssert("some text remains", () => textBox.Text == "test123 $$$aaa 5.5...");
-            AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("some text remains", () => textBox.Text == " $$$aaa 5.5...");
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
-            AddAssert("some text remains", () => textBox.Text == "aaa 5.5...");
-            AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("some text remains", () => textBox.Text == " 5.5...");
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("some text remains", () => textBox.Text == ".5...");
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
-            AddAssert("some text remains", () => textBox.Text == "5...");
-            AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("some text remains", () => textBox.Text == "...");
             AddStep("delete first word", () => InputManager.Keys(PlatformAction.DeleteForwardWord));
             AddAssert("text is empty", () => textBox.Text.Length == 0);
diff --git a/osu.Framework/Graphics/UserInterface/TextBox.cs b/osu.Framework/Graphics/UserInterface/TextBox.cs
index 71b2a5f51..2548d671d 100644
--- a/osu.Framework/Graphics/UserInterface/TextBox.cs
+++ b/osu.Framework/Graphics/UserInterface/TextBox.cs
@@ -490,6 +490,15 @@ private static int findNextWord(string text, int position, int direction)
 
                         continue;
 
+                    case WordTraversalStep.Symbol:
+                        if (char.IsLetterOrDigit(character))
+                            currentStep = WordTraversalStep.LetterOrDigit;
+                        else if (char.IsWhiteSpace(character))
+                            break;
+
+                        position += direction;
+                        continue;
+
                     case WordTraversalStep.LetterOrDigit:
                         if (char.IsLetterOrDigit(character))
                         {
@@ -498,13 +507,6 @@ private static int findNextWord(string text, int position, int direction)
                         }
 
                         break;
-
-                    case WordTraversalStep.Symbol:
-                        if (char.IsLetter(character) || char.IsWhiteSpace(character))
-                            break;
-
-                        position += direction;
-                        continue;
                 }
 
                 break;
```

</details>

**Comment by smoogipoo** [comment]
For the second example, that was a mistake fixed in https://github.com/ppy/osu-framework/pull/6496/commits/788f1a58800fd40a6de8da868478152776b78190. I can't repro the third example, not sure what happened there.

I'll yield on the symbol an letter thing. I don't fully agree with it - the fact that selecting `$$$aaa` backwards and forwards results in two completely different operations doesn't sit right by me, and is shining a spotlight onto the special behaviour of symbols. It's why I wanted to keep things simple and not have this special case.

Please check if you're okay with the latest behaviour so we can get this merged.

**Review by peppy — APPROVED** [review]
