### PR TITLE
Fix double click behavior regression

### LINKED ISSUE #1827: TextBox regression/unintended behavior? Double click-drag doesn't work as expected.
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Graphics/UserInterface/TextBox.cs
Due to the way double click logic is implemented. (Double click callback is called after the second click's release) double-click to select can act odd in some situations.

When you click twice but don't let go of your second click OnDoubleClick is never called so doubleClickWord is never set and thus when you drag, it selects as if you clicked once. This leads to tripple clicking+dragging seeming to work how you would expect double click+drag to work for the reason explained below.

When you double-click a word doubleClickWord is set to the bounds of the word clicked. This works as expected. However when you click and drag again the drag function checks for doubleClickWord and uses it to select by word. So if you double click on a word then click-drag elsewhere it selects all words in between the starting position of the original word clicked on and your dragging position instead of starting a new selection like you might expect.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/62784875-textbox-regression-unintended-behavior-double-click-drag-doesn-t-work-as-expected?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ekrctb**
Double click event should fire on second mouse down, not mouse up.
- Fix #1827

---
Fix double click drag not working.

### CODE REVIEW

File: osu.Framework/Input/MouseButtonEventManager.cs [hunk 1]
```diff
@@ -118,6 +118,8 @@ public virtual void HandlePositionChange(InputState state)
             }
         }
 
+        protected bool BlockNextClick;
```
Comment (smoogipoo) [inline osu.Framework/Input/MouseButtonEventManager.cs]: Is there a reason for this to be protected set? Along with `DragStarted` and `LastClickTime` and `ClickedDrawable`?

It's not something that stops this PR but we should tighten access of variables in this class since modifying these things sounds like undefined behaviour.
