### PR TITLE
Further fixes/improvements to WebRequests

### LINKED ISSUE #1110: WebRequest cancellation and timeout improvements
WebRequest is currently using a threadpool thread per request to check for timeouts. This can be replaced by using `.Wait()` on the two major async tasks (`response.Content.ReadAsStreamAsync` and `client.SendAsync`).

Note that the cancellation token should also be passed in as an argument in `Wait`

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes #1110 

1. Makes timeouts use cancellation tokens.
2. Fixes timeout retries.
3. Improves the use of async/await.
4. Makes use of cancellation tokens more reliable.

### CODE REVIEW

File: osu.Framework/IO/Network/WebRequest.cs [hunk 1]
```diff
@@ -317,7 +325,8 @@ public Task PerformAsync()
                     foreach (var kvp in Headers)
                         request.Headers.Add(kvp.Key, kvp.Value);
 
-                    response = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken.Token).Result;
+                    reportForwardProgress();
+                    response = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, linkedToken.Token).Result;
```
Comment (peppy) [inline osu.Framework/IO/Network/WebRequest.cs]: change to `await`

Comment (peppy) [reply osu.Framework/IO/Network/WebRequest.cs]: as discussed, don't change to `await` for now

File: osu.Framework/IO/Network/WebRequest.cs [hunk 2]
```diff
@@ -11,39 +11,61 @@
...
+        public bool Aborted { get; private set; }
+
+        private bool completed;
+        /// <summary>
+        /// Whether the <see cref="WebRequest"/> has been run.
+        /// </summary>
+        public bool Completed
+        {
+            get { return completed; }
+            set
```
Comment (peppy) [inline osu.Framework/IO/Network/WebRequest.cs]: should not be public

**Comment by peppy** [comment]
No way to disable/choose number of retries any more?

untitled

File: osu.Framework.Tests/IO/TestWebRequest.cs [hunk 3]
```diff
@@ -74,42 +79,207 @@ public void TestBadStatusCode(bool async)
...
             bool hasThrown = false;
-            request.Finished += (webRequest, exception) => hasThrown = exception != null;
+            request.Finished += exception => hasThrown = exception != null;
 
             if (async)
                 Assert.DoesNotThrowAsync(request.PerformAsync);
             else
                 Assert.DoesNotThrow(request.Perform);
 
+            Assert.IsTrue(request.Completed);
```
Comment (peppy) [inline osu.Framework.Tests/IO/TestWebRequest.cs]: why does this not throw?

Comment (peppy) [reply osu.Framework.Tests/IO/TestWebRequest.cs]: i mean all 4xx 5xx exceptions should be throwing exceptions, but it looks like they aren't at the moment.

**Comment by peppy** [comment]
Think this is looking good now 👍
