### PR TITLE
Move exception from FlowContainer to FillFlowContainer

### LINKED ISSUE #2013: FlowContainer throws exception when it doesn't need to
`FlowContainer` currently throws an exception when one of it's children has `child.RelativeSizeAxes & container.AutoSizeAxis != 0`. However, it doesn't need to when `FillFlowContainer` doesn't even flow in that direction.

Example:
image
Both the seperator and the country sit inside a `FillFlowContainer`. That container is autosized in both directions but only flows vertically. The seperator has its x-axis relatively sized and only depends on the width of the country. The container and the separator don't depend on each other but the `FillContainer` still throws an exception.

### PR DESCRIPTION
**Pull request by jorolf**
FlowContainer doesn't know how its subclasses handle to position of its children
- Fixes #2013 
- Also removes duplicated exception in [FlowContainer.cs#L171](https://github.com/ppy/osu-framework/blob/7b42ec941ffa3ff342292f9fa856112a6aca477f/osu.Framework/Graphics/Containers/FlowContainer.cs#L171) and [FlowContainer.cs#L207](https://github.com/ppy/osu-framework/blob/7b42ec941ffa3ff342292f9fa856112a6aca477f/osu.Framework/Graphics/Containers/FlowContainer.cs#L207)

### CODE REVIEW

File: osu.Framework/Graphics/Containers/FlowContainer.cs [hunk 1]
```diff
@@ -228,4 +232,25 @@ public FlowTransform()
             }
         }
     }
+
+    /// <summary>
+    /// Represents the direction children of a <see cref="FlowContainer{T}"/> should flow in.
+    /// </summary>
+    public enum FlowDirection
```
Comment (UselessToucan) [inline osu.Framework/Graphics/Containers/FlowContainer.cs]: I suggest to use `Axes` enum instead. `Direction = Axes.X` does not look that bad to me.

File: osu.Framework/Graphics/Containers/FlowContainer.cs [hunk 2]
```diff
@@ -168,19 +173,18 @@ private void performLayout()
...
 
                 // In some cases (see the right hand side of the conditional) we want to permit relatively sized children
                 // in our flow direction; specifically, when children use FillMode.Fit to preserve the aspect ratio.
                 // Consider the following use case: A flow container has a fixed width but an automatic height, and flows
                 // in the vertical direction. Now, we can add relatively sized children with FillMode.Fit to make sure their
                 // aspect ratio is preserved while still allowing them to flow vertically. This special case can not result
                 // in an autosize-related feedback loop, and we can thus simply allow it.
-                if ((d.RelativeSizeAxes & AutoSizeAxes) != 0 && (d.FillMode != FillMode.Fit || d.RelativeSizeAxes != Axes.Both || d.Size.X > RelativeChildSize.X || d.Size.Y > RelativeChildSize.Y || AutoSizeAxes == Axes.Both))
+                if ((d.RelativeSizeAxes & AutoSizeAxes & (Axes)FlowDirection) != 0 && (d.FillMode != FillMode.Fit || d.RelativeSizeAxes != Axes.Both || d.Size.X > RelativeChildSize.X || d.Size.Y > RelativeChildSize.Y || AutoSizeAxes == Axes.Both))
```
Comment (UselessToucan) [inline osu.Framework/Graphics/Containers/FlowContainer.cs]: I don't like this `(Axes)FlowDirection` cast.

File: osu.Framework/Graphics/Containers/FlowContainer.cs (hunk 1 above)
Comment (jorolf) [reply osu.Framework/Graphics/Containers/FlowContainer.cs]: What would `Axes.None` do?

Comment (UselessToucan) [reply osu.Framework/Graphics/Containers/FlowContainer.cs]: We can throw an `ArgumentException`.

Comment (jorolf) [reply osu.Framework/Graphics/Containers/FlowContainer.cs]: What if we wanted to implement something like a "reverse full" where it fills the y direction first?

@peppy @smoogipoo do you have any opinions on this?

File: osu.Framework/Graphics/Containers/FillFlowContainer.cs [hunk 3]
```diff
@@ -41,19 +41,19 @@ public class FillFlowContainer : FillFlowContainer<Drawable>
...
+        private FlowDirection direction = FlowDirection.Full;
 
         /// <summary>
-        /// If <see cref="FillDirection.Full"/> or <see cref="FillDirection.Horizontal"/>,
+        /// If <see cref="Containers.FlowDirection.Full"/> or <see cref="Containers.FlowDirection.Full"/>,
         /// <see cref="Container{T}.Children"/> are arranged from left-to-right if their
         /// <see cref="Drawable.Anchor"/> is to the left or centered horizontally.
         /// They are arranged from right-to-left otherwise.
-        /// If <see cref="FillDirection.Full"/> or <see cref="FillDirection.Vertical"/>,
+        /// If <see cref="Containers.FlowDirection.Full"/> or <see cref="Containers.FlowDirection.Full"/>,
```
Comment (HoLLy-HaCKeR) [inline osu.Framework/Graphics/Containers/FillFlowContainer.cs]: Duplicate `Containers.FlowDirection.Full` in docs?

**Comment by peppy** [comment]
I think this looks okay. @Tom94 could you please double-check this before merge?

File: osu.Framework/Graphics/Containers/FillFlowContainer.cs [hunk 4]
```diff
@@ -132,6 +132,17 @@ protected override IEnumerable<Vector2> ComputeLayoutPositions()
             {
                 Drawable c = children[i];
 
+                // In some cases (see the right hand side of the conditional) we want to permit relatively sized children
+                // in our fill direction; specifically, when children use FillMode.Fit to preserve the aspect ratio.
+                // Consider the following use case: A fill flow container has a fixed width but an automatic height, and fills
+                // in the vertical direction. Now, we can add relatively sized children with FillMode.Fit to make sure their
+                // aspect ratio is preserved while still allowing them to fill vertically. This special case can not result
+                // in an autosize-related feedback loop, and we can thus simply allow it.
+                if ((c.RelativeSizeAxes & AutoSizeAxes & (Axes)Direction) != 0 && (c.FillMode != FillMode.Fit || c.RelativeSizeAxes != Axes.Both || c.Size.X > RelativeChildSize.X || c.Size.Y > RelativeChildSize.Y || AutoSizeAxes == Axes.Both))
```
Comment (Tom94) [inline osu.Framework/Graphics/Containers/FillFlowContainer.cs]: I would prefer a helper method (e.g. `Axes toAxes(Direction dir)`) over the cast to avoid breakage in the future.

File: osu.Framework/Graphics/Containers/FlowContainer.cs [hunk 5]
```diff
@@ -168,19 +168,7 @@ private void performLayout()
...
-                // in our flow direction; specifically, when children use FillMode.Fit to preserve the aspect ratio.
-                // Consider the following use case: A flow container has a fixed width but an automatic height, and flows
-                // in the vertical direction. Now, we can add relatively sized children with FillMode.Fit to make sure their
-                // aspect ratio is preserved while still allowing them to flow vertically. This special case can not result
-                // in an autosize-related feedback loop, and we can thus simply allow it.
-                if ((d.RelativeSizeAxes & AutoSizeAxes) != 0 && (d.FillMode != FillMode.Fit || d.RelativeSizeAxes != Axes.Both || d.Size.X > RelativeChildSize.X || d.Size.Y > RelativeChildSize.Y || AutoSizeAxes == Axes.Both))
-                    throw new InvalidOperationException(
-                        "Drawables inside a flow container may not have a relative size axis that the flow container is auto sizing for." +
-                        $"The flow container is set to autosize in {AutoSizeAxes} axes and the child is set to relative size in {d.RelativeSizeAxes} axes.");
+                    break;
```
Comment (Tom94) [inline osu.Framework/Graphics/Containers/FlowContainer.cs]: Why remove this exception and `break` instead? If the exception was truly duplicate and can never occur here, then shouldn't we simply remove the entire if-statement and replace it with an assertion?

Comment (jorolf) [reply osu.Framework/Graphics/Containers/FlowContainer.cs]: That exception is also in line 207. It even has the same exception message.

Comment (Tom94) [reply osu.Framework/Graphics/Containers/FlowContainer.cs]: Sorry, I completely overlooked that. All good. :)

File: osu.Framework/Graphics/Containers/FillFlowContainer.cs (hunk 4 above)
Comment (jorolf) [reply osu.Framework/Graphics/Containers/FillFlowContainer.cs]: What kind of method? local, private or extension?
