### PR TITLE
Use macOS fullscreen window mask instead of changing resolution

### LINKED ISSUE #1598: Changing from borderless to windowed on macOS causes a hard crash
Also fullscreen doesn't work. Probably related.

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/59294966-changing-from-borderless-to-windowed-on-macos-causes-a-hard-crash?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F44024461&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by swoolcock**
Apple recommends not changing the user's desktop resolution.  Instead we should use the `toggleFullscreen` selector and set the presentation options to hide the menu and dock.

Also moved these calls onto the `InputThread`, which is the OpenTK thread that accesses the main run loop.

Fixes #1598 
Fixes ppy/osu#3047

Edit: Note that while this PR will prevent the crashing and make fullscreen "work", ultimately the entire window state management implementation for macOS needs to be rewritten in OpenTK.  Some of the windowing concepts in macOS do not map one-to-one with OpenTK's states, and the current implementation also uses a lot of deprecated functions.

### CODE REVIEW

**Comment by peppy** [comment]
- After entering fullscreen you cannot bring the menu up by holding cursor at top of screen like any other macOS app.
- Manually exiting from mission control does not update the game setting. It will still start in fullscreen next run.

**Comment by swoolcock** [comment]
> After entering fullscreen you cannot bring the menu up by holding cursor at top of screen like any other macOS app.

This is how OpenTK currently works for fullscreen on macOS, so I kept that functionality.  It's much easier to leave the menu/dock there on autohide if you prefer.

> Manually exiting from mission control does not update the game setting. It will still start in fullscreen next run.

Do we not want the game to remember whether it was fullscreen?

**Comment by peppy** [comment]
The default behaviour should exist for menu pop-in. That's how most people are used to exiting fullscreen.

**Comment by swoolcock** [comment]
No problem, will change it.  What about the dock autohide?  That's a separate flag so it could be disabled, but I assume we want the same behaviour as the the menu.

**Comment by peppy** [comment]
Can we easily change it in the future? If so I'd go with pure defaults to begin with for conformity (dock autohide enabled)

**Comment by swoolcock** [comment]
Also fixes: https://github.com/ppy/osu/issues/3047

File: osu.Framework/Platform/MacOS/Native/NSApplication.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
+﻿// Copyright (c) 2007-2018 ppy Pty Ltd <contact@ppy.sh>.
+// Licensed under the MIT Licence - https://raw.githubusercontent.com/ppy/osu-framework/master/LICENCE
+
+using System;
+
+namespace osu.Framework.Platform.MacOS.Native
+{
+    internal struct NSApplication
```
Comment (peppy) [inline osu.Framework/Platform/MacOS/Native/NSApplication.cs]: i think this can be made a `static class`

Comment (swoolcock) [reply osu.Framework/Platform/MacOS/Native/NSApplication.cs]: This will never be instantiated, so agreed that a `static class` makes sense; same for `NSNotificationCenter`.  `NSArray` etc. do need to be instantiated though.

**Comment by swoolcock** [comment]
Once #1729 is merged I will probably change this PR slightly to utilise the additional `UpdateFrame` event handler rather than hooking into the `InputThread`.  It should make the implementation a bit cleaner.

**Comment by swoolcock** [comment]
What's the go with this PR?  I need to make some changes to `MacOSGameWindow` soon to fix the cursor disappearing over the autohide menu.  Semi-regression caused by https://github.com/ppy/osu-framework/pull/1729

Also looking at these cases related to the cursor position, which will possibly require a change to this file. https://github.com/ppy/osu-framework/issues/1380 https://github.com/ppy/osu-framework/issues/1331

**Comment by peppy** [comment]
Still haven't had a chance to properly review, will likely get to it today.
