### PR TITLE
Fix binding leased to bindable potentially throwing exceptions

### LINKED ISSUE #3108: Binding to a leased bindable provides unexpected behaviour
Binding to a leased bindable doesn't allow changing the value. It probably should.

```csharp
var copy = leased.GetBoundCopy();
copy.Value = "test"; // works
```

```csharp
var copy = new BindableString();
leased.BindTo(copy);
copy.Value = "test"; // doesn't work
```

### PR DESCRIPTION
**Pull request by iiSaLMaN**
- Forgotten override after addition of modifiable `Default` in #3123

Closes #3108

### CODE REVIEW

File: osu.Framework/Bindables/LeasedBindable.cs [hunk 1]
```diff
@@ -73,6 +73,20 @@ public override T Value
...
+        {
+            get => base.Default;
+            set
+            {
+                if (source != null)
+                    checkValid();
+
+                if (EqualityComparer<T>.Default.Equals(Default, value)) return;
+
+                SetValue(base.Default, value, true);
```
Comment (smoogipoo) [inline osu.Framework/Bindables/LeasedBindable.cs]: SetValue?

File: osu.Framework.Tests/Bindables/BindableLeasingTest.cs [hunk 2]
```diff
@@ -263,5 +263,28 @@ public void TestUnbindAllReturnsLease()
             leased.UnbindAll();
             leased.UnbindAll();
         }
+
+        [Test]
+        public void TestBindingToLeased()
+        {
+            var leased = original.BeginLease(false);
+
+            var copy1 = leased.GetBoundCopy();
```
Comment (smoogipoo) [inline osu.Framework.Tests/Bindables/BindableLeasingTest.cs]: So “copy” that is a copy of the leased here, but “copy2” is a completely separate bindable below?

Please split into multiple testcases and name the methods based on what they test (look at all other methods in this class), and rename the variables to be more descriptive.

File: osu.Framework/Bindables/LeasedBindable.cs (hunk 1 above)
Comment (iiSaLMaN) [reply osu.Framework/Bindables/LeasedBindable.cs]: oops

File: osu.Framework/Bindables/Bindable.cs [hunk 3]
```diff
@@ -118,11 +118,11 @@ public virtual T Default
 
                 if (EqualityComparer<T>.Default.Equals(defaultValue, value)) return;
 
-                setDefault(defaultValue, value);
+                SetDefault(defaultValue, value);
             }
         }
 
-        private void setDefault(T previousValue, T value, bool bypassChecks = false, Bindable<T> source = null)
+        protected void SetDefault(T previousValue, T value, bool bypassChecks = false, Bindable<T> source = null)
```
Comment (smoogipoo) [inline osu.Framework/Bindables/Bindable.cs]:
```suggestion
        internal void SetDefault(T previousValue, T value, bool bypassChecks = false, Bindable<T> source = null)
```

**Comment by smoogipoo** [comment]
seems ok.
