### PR TITLE
Fix `Renderer` holding a permanent reference to every texture ever created

### LINKED ISSUE #5486: `Renderer` holds references to all textures indefinitely
Needs to be weak, or cleaned up at some point:

Parallels Desktop 2022-10-27 at 06 22 10

In most cases, the disposal is explicitly called so this does not add a huge overhead, but it's still an issue.

### PR DESCRIPTION
**Pull request by peppy**
Closes #5486.

### CODE REVIEW

File: osu.Framework/Graphics/Rendering/Dummy/DummyNativeTexture.cs [hunk 1]
```diff
@@ -21,6 +21,12 @@ internal class DummyNativeTexture : INativeTexture
         public bool UploadComplete => true;
         public bool IsQueuedForUpload { get; set; }
 
+        ulong INativeTexture.TotalBindCount
+        {
+            get => 0;
+            set => throw new System.NotImplementedException();
```
Comment (smoogipoo) [inline osu.Framework/Graphics/Rendering/Dummy/DummyNativeTexture.cs:27]: Probably shouldn't throw. Maybe `{ }` instead, if it works?

**Review by smoogipoo — CHANGES_REQUESTED** [review]

**Review by smoogipoo — APPROVED** [review]
