### PR TITLE
Throw InvalidCastException on retrieving a bindable from ConfigManage…

### LINKED ISSUE #2177: Attempting to retrieve a bindable from ConfigManager that is different from declared type throws wrong exception
It needs to throw an InvalidCastException instead of a Nullref.

For example, retrieving a `Bindable<float>` that is actually a double in the config store will result in a nullref.

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #2177

### CODE REVIEW

File: osu.Framework/Configuration/ConfigManager.cs [hunk 1]
```diff
@@ -149,7 +149,12 @@ private Bindable<U> set<U>(T lookup, U value)
         protected Bindable<U> GetOriginalBindable<U>(T lookup)
         {
             if (ConfigStore.TryGetValue(lookup, out IBindable obj))
-                return obj as Bindable<U>;
+            {
+                if (!(obj is Bindable<U>))
+                    throw new InvalidCastException();
```
Comment (smoogipoo) [inline osu.Framework/Configuration/ConfigManager.cs]: How about something like `InvalidCastException($"Cannot convert bindable of type {obj.GetType()} retrieved from {nameof(ConfigManager<T>)} to {typeof(Bindable<U>)}.")`
