### PR TITLE
Fix audio track playing beyond expiry/disposal in edge cases

### LINKED ISSUE #37136: Audio overlap occurs occasionally when switching songs after 2026.326.x-tachyon updates
### Type

Performance

### Bug description

After updating to version `2026.326.0-tachyon` or `2026.326.1-tachyon`, there is a chance that the audio of two songs plays simultaneously when switching between tracks.

I am not sure what triggers this issue, and it happens infrequently. I have only encountered it after several hours of use post-update. I am certain this problem did not occur before these updates.

### Screenshots or videos

https://github.com/user-attachments/assets/2b7ae590-9138-4ccc-8863-c6fd23b05a7f

### Version

2026.326.1-tachyon

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/26318921/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
This has haunted us many times now (previously, when [exiting gameplay](https://github.com/ppy/osu/pull/35966), required a local fix because we don't have `internal` access like we do here..)

Most recently, due to arbitrary changes in ordering/length of transitions at song select, there was a chance that a track would not get completely dimmed (to zero volume) before disposal. To emphasise, this was always an issue with the song select code, but it became audible to users in the [recent change](https://github.com/ppy/osu/pull/37022).

Should we use `UnbindAllBindables` for this purpose? It [wouldn't be the first time](https://github.com/ppy/osu-framework/blob/d682387998da77c4a27b0f3942c1b120de6f9666/osu.Framework/Graphics/Containers/DelayedLoadWrapper.cs#L145) so maybe?

Does `DrawableSample` need the same treatment? Possibly, but even the `Dispose` flow doesn't handle stopping samples so I'd treat that as its own issue and fix.

Closes https://github.com/ppy/osu/issues/37136.

### CODE REVIEW

File: osu.Framework/Graphics/Audio/DrawableTrack.cs [hunk 1]
```diff
@@ -122,5 +122,13 @@ protected override void OnMixerChanged(ValueChangedEvent<IAudioMixer?> mixer)
             mixer.OldValue?.Remove(track);
             mixer.NewValue?.Add(track);
         }
+
+        internal override void UnbindAllBindables()
+        {
+            base.UnbindAllBindables();
+
+            // Relying on disposal for this can cause delays before audio stops playing.
+            StopAsync();
```
Comment (bdach) [inline osu.Framework/Graphics/Audio/DrawableTrack.cs]: From the reliability angle, I guess I understand why this is calling the async variant and not the sync one, but calling it like this is asking for unobserved exceptions if any to kill the game.

From the correctness angle: Drawable audio wrappers have been dodgy at best for a long time in terms of association between the drawable / rendering subsystem and the audio subsystem. These wrappers are pretending to tie one to the other but not really doing a good job of it. Audio playback via these wrappers does not adhere to laws of drawables such as lifetime, presence, removal from hierarchy and such. To that end this does *a little* to make that actually work but I'm not sure that it's doing enough. My suggestion would be something like

```diff
diff --git a/osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs b/osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
index 41bcc707b2..6e9a748768 100644
--- a/osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
+++ b/osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs
@@ -132,12 +132,19 @@ private void refreshLayoutFromParent()
                 OnMixerChanged(new ValueChangedEvent<IAudioMixer>(parentMixer, newMixer));
 
             parentMixer = newMixer;
+
+            if (newAdjustments == null && newMixer == null)
+                OnParentLost();
         }
 
         protected virtual void OnMixerChanged(ValueChangedEvent<IAudioMixer> mixer)
         {
         }
 
+        protected virtual void OnParentLost()
+        {
+        }
+
         internal override void UnbindAllBindables()
         {
             base.UnbindAllBindables();
diff --git a/osu.Framework/Graphics/Audio/DrawableTrack.cs b/osu.Framework/Graphics/Audio/DrawableTrack.cs
index 0621668528..fa69ca646a 100644
--- a/osu.Framework/Graphics/Audio/DrawableTrack.cs
+++ b/osu.Framework/Graphics/Audio/DrawableTrack.cs
@@ -7,6 +7,7 @@
 using osu.Framework.Audio.Mixing;
 using osu.Framework.Audio.Track;
 using osu.Framework.Bindables;
+using osu.Framework.Logging;
 
 namespace osu.Framework.Graphics.Audio
 {
@@ -123,12 +124,10 @@ protected override void OnMixerChanged(ValueChangedEvent<IAudioMixer?> mixer)
             mixer.NewValue?.Add(track);
         }
 
-        internal override void UnbindAllBindables()
+        protected override void OnParentLost()
         {
-            base.UnbindAllBindables();
-
-            // Relying on disposal for this can cause delays before audio stops playing.
-            StopAsync();
+            base.OnParentLost();
+            StopAsync().ContinueWith(t => Logger.Log($"Failed to stop audio track on losing parent: {t.Exception}"), TaskContinuationOptions.OnlyOnFaulted);
         }
     }
 }

```

instead. Interested in @smoogipoo opinion though.

Comment (peppy) [reply osu.Framework/Graphics/Audio/DrawableTrack.cs]: That's actually what I started with. Then I noticed that there are still cases we aren't using mixers which means that the parent mixer may be always `null`.

And yeah, I was wanting to call `FireAndForget` which doesn't exist here. Adding exception handling is required.

Comment (bdach) [reply osu.Framework/Graphics/Audio/DrawableTrack.cs]: I guess `cursor == null` as the guard condition instead maybe.

Comment (smoogipoo) [reply osu.Framework/Graphics/Audio/DrawableTrack.cs]: I very slightly agree with this suggestion just because it makes it a bit more explicit about what's happening. But keep it `internal` not `protected`.

Comment (peppy) [reply osu.Framework/Graphics/Audio/DrawableTrack.cs]: 53e685acea69cfdc244985796005b8788526fdb5 i guess? I'm not feeling this but it's neither here not there.

File: osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs [hunk 2]
```diff
@@ -104,6 +104,8 @@ private void refreshLayoutFromParent()
             IAggregateAudioAdjustment newAdjustments = null;
             IAudioMixer newMixer = null;
 
+            bool hadParent = Parent != null;
```
Comment (bdach) [inline osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs]: I'm fine with this code-wise but the past tense in the variable name is tripping me up and I can't tell if it's a typo or intentional. I'd expect `hasParent` because it's the *current* parent state this is checking not the past one... is it?

Comment (peppy) [reply osu.Framework/Graphics/Audio/DrawableAudioWrapper.cs]: Yeah dunno, it was intentional because of the cursor logic afterwards, but I can rename it.

**Review by bdach — APPROVED** [review]
Seems alright
